# Generated by Django 5.1.6 on 2025-02-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_cylinder_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cylinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cylinder'),
        ),
    ]
